language: ruby
rbenv:
- 2.5.3
env:
  global: 
    secure: 
addons:
  postgresql: 9.6
before_install:
- gem install bundler:2.1.4
- nvm install --lts
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key:
    secure: Gmh4go0+B9XBFr0GDGIrgQcCVcMklkVJH8QKTegq3VEVICEBx2aIAGqYCkKFD2qd/o7Pu1J/JGfdN3gu9MPlFx6nzXfWoZlq/GzBZmbJc+rsR2ry9Tn5RAsjAczICOlWPo9B0LjdpUiwNqmz5KScgjSX7f34tbTPbklsZmMLDQ5CRTgS4I7MNHhP7tdr92zcOd0X1ely1oyZQdKjemoVJXU4DDbKEy234LQnYiBCh7IgZWIFrerwzPokfDMNPXFXiEloTgpOUGf/EWW5aPc94X7U4lSA9SBekEZ78T4dI7NL3KjYUmRpkA0rlPgWhIm/2xjnHf3+mtgJ6RtOoFm8I+aw0X60cnjFDnFAYP/0CFpUkr3CV0shlcV7QNfe02TrtHzDnfVihP39vKBjrerioUNFGJyVImmDjZEsKyfk9ZSdJEs2TXvvMvTjXkTfwpH5ty+JR/Ewt860ChIHilW3FaShbK0vdE0RVdzeYoqEVgbzZcPF6zvPkPqiL+YJF6aqvfvBWTaGk96t5VsfDmV8/c4W6MysyYREj8TKR62JKzTAsYMgHLOPchpUD1oCerFZ05xOr6m9W2BrOv4c3FkMpGDewpoeyzyfHFKqT8keZS+yWpsZb748DXDsCzmpjl7iGfy4o0LroUV8Y27sxMG6Q4e75MnvdGTXt9Q7WGtxAO8=
  app: rail-engine
  on:
    repo: MGonzales26/rails-engine
    branch: main
  skip_cleanup: 'true'
