language: ruby
rbenv:
- 2.5.3
addons:
  postgresql: 9.6
before_install:
- gem install bundler:2.1.4
- nvm install --lts
script:
- bundle exec rails db:{create,migrate} RAILS_ENV=test
- bundle exec rspec
deploy:
  provider: heroku
  api_key: HEROKU_API_KEY
    # secure: oTBJW9StjMhKFp0dFToL1cTu2FFjD+QKs9DhqYb24/Vtjqbt9CJGw6lLSToqktopri/N1wkdOjGw84zj1fPX5oP0IRi+/Wzl02a7onJB8vp2SABbEIyYXufQSXFpNNtunvT8gp/xg+7sPAF6XS4rYjTcGUJ0l3t6cWkTxieLtVdlqVK+HVpraDiD8UdyjoJCBRTBHON7RU+wLyzm2lHbK9gLLm9xvEBwDROVNZDKQVcBMn8dY55B8Rzrbb7MzikHM4zdu/7DZ2Q3TEOoAGy/AJfUMXT9HilUf7/gmkmMiTkzkLaclwYFsPLizWcUrc6itvOhBHNREZBi1PfmTV81fr4ayd43lm7PGYgulcaX63rGuLSPkyWp9yXf9xFQ3a+V8fBSwiM4f1fniXlKch701Dp2WKblq7QNYUKKgLX33cPPEZiszXhJDHQhi+ggOPeFHPOHLSNcn8MQKZafnCbeSTaChMXWr8B8Jhw77TO4luxTPbP2B183QLeovIF7Q7dEUECGKq1i0gYITNaWhawgcIM7kDlayjHCw+ZDSlxLXmmgWbE4Lsj73ka+bQrUuJfYYNAT/SAuRvPsA67E1jOym8siH/Zv1iITpav/h7BUdUL/fR2p3pry/6S5bNxL5OoPavXgdoXdk5+Iz7JuXz3psh8APVyRH6CgcBZXmiwdmsY=
    # secure: gR+ylXis9ju1YJskEQM4ZhYBhDypj5UdKzvsr3+6de36UuOaroKRIWP5msXH4V3hd/WfSTgt1Xf/mlk5hx0li/lzXE5bjmmXLxWYsGww+LS3bbdOMc2vkrCa6sj8Sq716NdjVAH30fEkByASKUN0pHld55ac8QYHuzFxnMKMFL1PKxggDlPgT9ieBVLpeN7B4GQ/VBblzujAC3k8uhMOhvDfqFo85QBhjCAVpCD7sR3NDYLQchyORBdz+4OkxIQ1ngVgNF5YwuTL5KwfBj/ES/7cRb+8EEu/ExSpXUCwPgVlE/fY47dUBCTVD+vjJ4T0n/JiNhOps/b9EMixbU5HAL03Uei5nWlvOsfvSBEEVbbdL81b/v66xOuxpZ/fN17y4OlZPQ4yTQPKU/97VqhKnlmM+Q3WH7XSKDBYzKCdaWTbqi+LeJukCCywSpigWDwgnta6pjvqW65ilxr3UUjs24GF7XRgFpG8SZRSCSvPSgLdYEYNnM0ZT8Zv513glyl6ycj1nVJtZkc9Lr3YccflBr4bj6mtdfUWLs6mEHUTWAsJAii29ISk5xY1TZxiF+NoPt8RrVbbXoR+iiBjLYEg6LiOVumcQoDIIn/imxuybJPzobs0v1KfUm4a6EMZMf7Vi2WjvekJSwszj4XMM37May3V4s5iehc7vZ5gaXUkewI=
  on:
    branch: main  
  app: rail-engine
  run: rails db:migrate
# env:
#   global:
#     # secure: OAvTI6k2mfczc5RwRVAAQJnxCGOR1C3iPk7GYzWsnSBxGSJZkBUHPL64yn5P4oAefTaJ74x2YNaMmy04/yLB5XADTfIcr9QHcBtCQE18CbqPNRZolUCy8HseT4SN/PCgUwlM6/i+iUjl/vaUx4nldDpTYTmsR8G7d9xXTuvZNIT8aFoGaTyc/c6NpOYEbN/1pSCxE5DKUNjgdsPzUBkIfkHmR7THDADUCFfD7Zb28/jboeNgdU+AlN5vHDJ1tsrC1TfvZZ4lvAYaX/ZuiIv1tsZLRi/UJNkgs/40KxTrz6IBjd43xpjezISPEqWsXKZcSHIFbyDHkWFxzdPf0dTO2JYq5lyqXO7qShtt9vOQBoWb4SUjyV/PNMZA8FTP0uKtVywfPJTFYIRcFmrPLBuDKq4zSWmo8pqf1KYoPXJrVPH2U0TOmoBluVy7e3Gq3ZjouFkrTSv0KTqRNJG3KoYvQsgNnIe63Adnztt1N0Xzy0UEt2Z60ynT52zperRwscHIz07AiW2K2dhGJpCoA+VzdEkC+1m7Vuo6by/YR0IFMV13t/vF+G4VK22Ohq2LNGiZk+g8BMVLHAi2GM3lfvSxqQji2sSSaNPPfxMujF4MIuc1F9YztEKnU8zJiDep8cV/K043JmzQfSobATjmrG2uB88WupbpXc/n1H6j0Dmd2R0=
#     secure: Q9q2bpu+mvNe1cXECILKtd7+ktV/Yf/ng1k41vBlrYzUiVUhvzMzUTDYKqFwjJfZTfC3T4qNPKY8X3EAAXz5UcWzLW8p6VjJCc9/akzstGi5ctArF44Fl7mLrS8PnwJXFsg6tt48FuaBC8TaKaDGvMNXFwo+9wgplAO3PVMlpJbLsTXkzFmQvlYAnStdSI2lN67q7U5Pa+/6SLQ9lJLQI4RbRTe3clC4OKsV6l/7t3UgKom07IWgZ/z2E8H88TBfCaMKX1MoamdBrEnflOKEuI+TLxIghLEhGWxkPPdRSfESBTJTDpL0UkDLI4ii+PQQHSojtje9XlXerH7xqzogSjzaB6D+OCYJQ/yrT9hwfTAAlfBEDQFsF/NJQZ0zyJwuB+ByQcCU6IS9EuFCq9VAB25pflyWm4gWIHGQJZKf0/r16ibMrnjV4pmh1ZhXOwApnqpblIIs6Ji6h4bkyUQBzjQEog7sHwT0hMNwNHDH2hFL2XS2LZk7lPe+YIAgwupwKeRIcd8wsdwxAzA8nH9Xn9ibMciJEQNnGwQQR9xWQZbggyg1Tatj683GApMTCI4oo71H05e0SY4/srUlyLbFgO+3JPv5YsuOYcG0mAegEzfs9RO+5Ui8vUOKxmizMBGYn1PZy1pgShHZpTfAqgjRW1jvEKGSeiasZeyBL2Nz7H8=



# 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 rail-engine:github token