version: 2.1
orbs:
  ruby: circleci/ruby@1.1.3 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.3
      - image: circleci/postgres:13.2
        environment:
          POSTGRES_USER: rails-engine
          POSTGRES_DB: rails_engine_test
          POSTGRES_HOST_AUTH_METHOD: trust
    steps:
      - checkout
      - run:
          name: Configure Bundler
          command: |
            gem update --system
            gem install bundler
      - run:
          name: Bundle
          command: bundle install
      - run: sudo apt install -y postgresql-client || true
      - run:
          name: Database Setup
          command: |
            bundle exec rake db:create
            bundle exec rake db:structure:load
  test:
    docker: 
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run:
          name: Test Suite
          command: bundle exec rspec

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build