version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    working_directory: ~/rails-engine
    docker:
      - image: circleci/ruby:2.5.3
    steps:
      - checkout
      - run:
          name: Bundle
          command: bundle install
      - run:
          name: Database setup
          command: bundle exec rails db:{create,migrate}
      - run:
          name: Test Suite
          command: bundle exec rspec

